### ISSUE TITLE
Fody got error wit everey businessclass (XPO)

### ISSUE THREAD

**Issue by CWolffIF** [eXpandFramework/eXpand#405]
Hi,

after I updated to 19.1.301.0 I got an compilation error with ervery business class and fody (see below).
If I delete the business class, the error is in the next businessclass.
If I uninstall fody, everthing works.

What is fody for and is there a trick to get the project run?

>MSBUILD : error : Fody: An unhandled exception occurred:
2>MSBUILD : error : Exception:
2>MSBUILD : error : Failed to execute weaver C:\DevProjects\NuGetPackages\PropertyChanged.Fody.2.6.1\build\..\netclassicweaver\PropertyChanged.Fody.dll
2>MSBUILD : error : Type:
2>MSBUILD : error : System.Exception
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    bei InnerWeaver.ExecuteWeavers()
2>MSBUILD : error :    bei InnerWeaver.Execute()
2>MSBUILD : error : Source:
2>MSBUILD : error : FodyIsolated
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Void ExecuteWeavers()
2>MSBUILD : error : Could not inject EventInvoker method on type 'iXISXRM.Module.BusinessObjects.iXIS.DataAttribute'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on iXISXRM.Module.BusinessObjects.iXIS.DataAttribute.
2>MSBUILD : error : Type:
2>MSBUILD : error : Fody.WeavingException
2>MSBUILD : error : StackTrace:
2>MSBUILD : error :    bei ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType)
2>MSBUILD : error :    bei ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType)
2>MSBUILD : error :    bei ModuleWeaver.FindMethodsForNodes()
2>MSBUILD : error :    bei ModuleWeaver.Execute()
2>MSBUILD : error :    bei InnerWeaver.ExecuteWeavers()
2>MSBUILD : error : Source:
2>MSBUILD : error : PropertyChanged.Fody
2>MSBUILD : error : TargetSite:
2>MSBUILD : error : Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)
2>MSBUILD : error :

**Comment by apobekiaris** [comment]
Fody implements behaviors at build time, it is integrated in base lib for years now. Fody is weaving assemblies that need the IPropertyChanged implementation. Its configuration in base is here https://github.com/eXpandFramework/eXpand/blob/master/Xpand/Xpand.Persistent/Xpand.Persistent.Base/FodyWeavers.xml

Nothing has changed there long time there.

It is not clear how u explicitly installed that package. If you can share more details?

**Comment by CWolffIF** [comment]
Hi,

the nuget packages Fody (4.2.1) and PropertyChanged.Fody (2.6.1) are automaticly installed with the nuget package eXpandlib.

If you uninstall fody the project works.

**Comment by apobekiaris** [comment]
hmm the lib nuspec had these dependencies in older versions as well
https://github.com/eXpandFramework/Support/blob/18.2/Nuspec/Lib.nuspec#L17-L25

https://github.com/eXpandFramework/eXpand/blob/master/Support/Nuspec/Lib.nuspec#L17-L25

**Comment by apobekiaris** [comment]
am I right that you use NuGets long time now?

**Comment by apobekiaris** [comment]
Thanks I see the problem now, Fody is a design time package and shouldn't be distributed. I ll update the Nuspecs for the next minor

**Comment by nurbed** [comment]
I have the same problem, but I don't see fody in the references list...
![image](https://user-images.githubusercontent.com/3589082/58011056-c9a12900-7af1-11e9-832f-b0ed97da6cc0.png)

how to uninstall fody?

**Comment by apobekiaris** [comment]
edit your csproj file and remove all related references.

**Comment by nurbed** [comment]
mmm... I have no references to Fody in any csproj file...
In a test project I removed the eXpandLib reference and all builds without problems... but if I remove the eXpandLib reference on my existing project, I receive some errors like this "error CS1705: Assembly 'Xpand.ExpressApp.Dashboard' with identity 'Xpand.ExpressApp.Dashboard, Version=19.1.301.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958' uses 'Xpand.Persistent.Base, Version=19.1.301.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958' which has a higher version than referenced assembly 'Xpand.Persistent.Base' with identity 'Xpand.Persistent.Base, Version=18.2.704.0, Culture=neutral, PublicKeyToken=c52ffed5d5ff0958'" 
Also after all sorts of cleaning and rebuild

**Comment by apobekiaris** [comment]
post a csproj that fails

**Comment by nurbed** [comment]
[XAFGarden.Module.csproj.zip](https://github.com/eXpandFramework/eXpand/files/3197452/XAFGarden.Module.csproj.zip)
this fails with the Fody error

**Comment by apobekiaris** [comment]
nope Fody is not responsible if that project fails, unless u posted a wrong project. What is the error u get?

**Comment by nurbed** [comment]
![image](https://user-images.githubusercontent.com/3589082/58016188-4ab1ed80-7afd-11e9-9c06-df296efa719f.png)
If I create a new project with these references all works... 
If in this project I add a reference to eXpandLib, I have this error on build:
 MSBUILD : error : Fody: An unhandled exception occurred:
1>MSBUILD : error : Exception:
1>MSBUILD : error : Failed to execute weaver C:\Users\nurbe\.nuget\packages\propertychanged.fody\2.6.1\build\..\netclassicweaver\PropertyChanged.Fody.dll
1>MSBUILD : error : Type:
1>MSBUILD : error : System.Exception
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 186
1>MSBUILD : error :    at InnerWeaver.Execute() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 109
1>MSBUILD : error : Source:
1>MSBUILD : error : FodyIsolated
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Void ExecuteWeavers()
1>MSBUILD : error : Could not inject EventInvoker method on type 'XAFTest.Module.BusinessObjects.Test.Table'. It is possible you are inheriting from a base class and have not correctly set 'EventInvokerNames' or you are using a explicit PropertyChanged event and the event field is not visible to this instance. Either correct 'EventInvokerNames' or implement your own EventInvoker on this class. If you want to suppress this place a [DoNotNotifyAttribute] on XAFTest.Module.BusinessObjects.Test.Table.
1>MSBUILD : error : Type:
1>MSBUILD : error : Fody.WeavingException
1>MSBUILD : error : StackTrace:
1>MSBUILD : error :    at ModuleWeaver.InjectMethod(TypeDefinition targetType, InvokerTypes& invokerType) in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:line 84
1>MSBUILD : error :    at ModuleWeaver.AddOnPropertyChangedMethod(TypeDefinition targetType) in C:\projects\propertychanged\PropertyChanged.Fody\MethodInjector.cs:line 28
1>MSBUILD : error :    at ModuleWeaver.FindMethodsForNodes() in C:\projects\propertychanged\PropertyChanged.Fody\MethodFinder.cs:line 237
1>MSBUILD : error :    at ModuleWeaver.Execute() in C:\projects\propertychanged\PropertyChanged.Fody\ModuleWeaver.cs:line 18
1>MSBUILD : error :    at InnerWeaver.ExecuteWeavers() in C:\projects\fody\FodyIsolated\InnerWeaver.cs:line 182
1>MSBUILD : error : Source:
1>MSBUILD : error : PropertyChanged.Fody
1>MSBUILD : error : TargetSite:
1>MSBUILD : error : Mono.Cecil.MethodDefinition InjectMethod(Mono.Cecil.TypeDefinition, InvokerTypes ByRef)
1>MSBUILD : error :

**Comment by nurbed** [comment]
but If I remove the reference to eXpandLib on my already created projects, the error is on the conflict between versions of xpand.persistent.base

**Comment by apobekiaris** [comment]
>C:\Users\nurbe.nuget\packages\propertychanged.fody\2.6.1\build..\netclassicweaver\PropertyChanged.Fody.dll

the XAF Test u use b4 has the above reference while your Garden project does not have it.

if u remove the above reference from the test solution it will work. My guess is that the Garden project u posted is not the right one. Look at the other projects in the solution. The package that fails is `propertychanged.fody`

Not in a few hours that will be low dependency nuget in our NugetServer if u afford to wait for them

**Comment by nurbed** [comment]
[XAFTest.zip](https://github.com/eXpandFramework/eXpand/files/3197530/XAFTest.zip)
If you can, try to build the sample

**Comment by apobekiaris** [comment]
I already said that the problem is with the Fody package which shouldn't distributed in the first place as it is a design time only package. I already improve the NuGet package algorithm so to minimize dependencies and handle case like this. In a few hours the bot will update this issue when the packages are in the NugetServer, use those instead and u should be able to complie with no issue.

**Comment by expand** [comment]
eXpand.lab release [19.1.301.1](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.1) includes commit [Minimize NuGet dependencies #405](https://github.com/eXpandFramework/eXpand.lab/commit/8ce4b4225cc6d79371a6f8f75333a66e6d766698) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by nurbed** [comment]
After the update to the 19.1.301.1 the sample project does not build due to the error:
MSBUILD : error : Fody: No weavers found for the configuration entries PropertyChanged. Add the desired weavers via their nuget package.

**Comment by apobekiaris** [comment]
yes you are right something went wrong with the build, I am checking now.

**Comment by apobekiaris** [comment]
when the next release try on a new sample, nuget does not remove dependencies.

**Comment by apobekiaris** [comment]
I see now the problem, it looks that by mistake I actually forgot the most important code commented, apologies for this, sending new build now, it won't be long.

https://github.com/eXpandFramework/eXpand.lab/blob/4ca365ef5633a6dd6cb2f0c1e1f369e1c019053e/Support/Build/CreateNuspecs.ps1#L149-L152

**Comment by expand** [comment]
eXpand.lab release [19.1.301.2](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.2) includes commit [Update Local Nuspecs for Validation #405](https://github.com/eXpandFramework/eXpand.lab/commit/2b7454698c04acf8231502406b524e1140e23b00) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by nurbed** [comment]
ok, the building is OK

now, in my project I have a reference to Xpad.ExpressApp.Security, that depend to Xpand.XAF.Modules.ModelViewInheritance
The latest version of this package depends to DevExpress.ExpressApp.v18.2 (18.2.7.0) and this break the program on startup...

**Comment by apobekiaris** [comment]
I found the the Nuspec versions were outdated, and fixed it. So when next release please test this scenario and we can then work out what happens in your solution.

1. Create and empty XAF solution
2. Goto your WinModule and install only the `eXpandSecurityWin` NuGet from the `Lab` servers. 
3. Then open your WinModule.cs and add this line in the constractor

```cs
RequiredModuleTypes.Add(typeof(XpandSecurityWinModule));
```
4. Build and you should have success no errors or warnings.
5. Try to run and you should get a message that `BaseImpl not found register it in your front end project...`, so install the `eXpandLib` package now in your front end project and you should be able to run.

Apply these steps to your solution and let me know if the problems are vanished.

**Comment by expand** [comment]
eXpand.lab release [19.1.301.3](https://github.com/eXpandFramework/eXpand.lab/releases/19.1.301.3) includes commit [Nuspecs version should be updated on each build #405](https://github.com/eXpandFramework/eXpand.lab/commit/980abdceea77574b6c2c4c080a1984aac8fcbc64) that relate to this task. Please test if it addresses the problem. If you use nuget add our LAB [NugetServer](https://xpandnugetserver.azurewebsites.net/nuget) as a nuget package source in VS.

Thanks a lot for your contribution.

**Comment by nurbed** [comment]
I followed the steps and the test project builds without problems, but on startup I still have a error on the reference to devexpress 18.2.7 not found

DevExpress.ExpressApp.DC.ObjectCreatingException: 'Unable to create an instance of the "Xpand.ExpressApp.Security.XpandSecurityModule" type.
Reason: "Non è stato possibile caricare il file o l'assembly 'DevExpress.ExpressApp.v18.2, Version=18.2.7.0, Culture=neutral, PublicKeyToken=b88d1754d700e49a' o una delle relative dipendenze. Impossibile trovare il file specificato."'

It seems to be related to the Xpand.XAF.Modules.ModelViewInheritance package

**Comment by apobekiaris** [comment]
can you post your sample?

**Comment by nurbed** [comment]
[XAFTest.zip](https://github.com/eXpandFramework/eXpand/files/3201159/XAFTest.zip)

**Comment by apobekiaris** [comment]
this solution does not contain any referelce to Xpand packages

**Comment by nurbed** [comment]
Sure? I reopened the project and there are the reference to eXpandSecurityWIn on XAFTest.Module.Win.csproj and eXpandLib on XAFTest.Win.csproj

**Comment by apobekiaris** [comment]
yes i am sure I d/l twice no expand refs nor packages.conf

**Comment by apobekiaris** [comment]
just a clean.ps1 which btw could be already in your system if u have xpand posh

https://github.com/eXpandFramework/XpandPosh/wiki/Clear-ProjectDirectories

**Comment by nurbed** [comment]
![image](https://user-images.githubusercontent.com/3589082/58076933-ba7eb180-7bab-11e9-81b8-103dd5e652e5.png)

![image](https://user-images.githubusercontent.com/3589082/58076954-d1bd9f00-7bab-11e9-952a-ec9ee9e9f722.png)

**Comment by apobekiaris** [comment]
that can explain a lot never tested packagerefernce

**Comment by nurbed** [comment]
YAY !!!!!
with the references in the packages.config file the test project works without problem ....
WTF :-)

**Comment by apobekiaris** [comment]
thats why i never tested packagereferenc, in my opinion and many other opinion it is problematic. it does not support init, scripts and there are endless packages out there that needs those events and with package reference simply not work. But I will research to see why it fails

**Comment by nurbed** [comment]
BINGO! 
I converted back my main project to the "package.config" manager and all works!

Many thanks

**Comment by apobekiaris** [comment]
u welcome i will update my finding about the package reference here but I will lock the post now. Feel free to open another if you have issues.

**Comment by apobekiaris** [comment]
Please subscribe to #414 get notified when packagereference format bug is fixed

**Comment by expand** [comment]
Closing issue for age. Feel free to reopen it at any time.

.Thank you for your contribution.
